canonical: https://www.medizininformatik-initiative.de/fhir/modul-studie
applyExtensionMetadataToRoot: false
id: mii-ig-studie
name: [DE] Medizininformatik Initiative - Medizinische Forschungsvorhaben - Implementierungsleitfaden - Version 2026.0.0
status: active
version: 2026.0.0
fhirVersion: 4.0.1
FSHOnly: false
packageId: de.medizininformatikinitiative.kerndatensatz.studie
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  hl7.fhir.extensions.r5: 4.0.1
  de.medizininformatikinitiative.kerndatensatz.meta: 2025.0.x

menu:
  Home: index.html
  Artifacts: artifacts.html
