# This workflow is copied from https://github.com/medizininformatik-initiative/kerndatensatz-meta/blob/master/.github/workflows/main.yml

name: CI (FHIR Validation)

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The workflow now runs using the meta repository
jobs:
  DOTNET_FHIR_VALIDATION:
    uses: medizininformatik-initiative/kerndatensatz-meta/.github/workflows/ci_dotnet_validation.yml@master
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      SUSHI_VERSION: ${{ vars.SUSHI_VERSION }}
    secrets: inherit

  JAVA_FHIR_VALIDATION:
    uses: medizininformatik-initiative/kerndatensatz-meta/.github/workflows/ci_java_validation.yml@master
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      PATH_TO_CONFORMANCE_RESOURCES: fsh-generated/resources
      PATH_TO_EXAMPLES: fsh-generated/resources
      JAVA_VALIDATION_ENABLED: true
      JAVA_VALIDATION_OPTIONS: ${{ vars.JAVA_VALIDATION_OPTIONS }}
      JAVA_VALIDATOR_VERSION: ${{ vars.JAVA_VALIDATOR_VERSION }}
    secrets: inherit